version: "3.7"

services:

  db:
    image: postgres:12-alpine
    container_name: wo_db
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      target: production_build
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: wo_server
    working_dir: /app
    command: [ "uvicorn", "main:app", "--reload", "--log-level", "debug","--host", "0.0.0.0", "--port", "80"]
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./app:/app

networks:
  internal:
    driver: bridge